#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# Fix some keys I need in VI mode
bindkey "^R" history-incremental-search-backward
bindkey '\e.' insert-last-word

if [ -f ~/.dircolors ]; then
  eval $(dircolors ~/.dircolors)
  zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
fi
